networks:
  keycloak-network:
    driver: bridge

services:
  mariadb-keycloak:
    image: mariadb:latest
    container_name: mariadb-keycloak
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: keycloakpassword
    ports:
      - 3306:3306
    networks:
      - keycloak-network

  mariadb-interview-coach:
    image: mariadb:latest
    container_name: mariadb-interview-coach
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: interviewcoach
      MARIADB_USER: interviewcoach
      MARIADB_PASSWORD: password
    ports:
      - 3307:3306

  keycloak:
    image: keycloak/keycloak
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb-keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
    ports:
      - "8080:8080"
    depends_on:
      - mariadb-keycloak
    volumes:
      - ./keycloak-realms:/opt/keycloak/data/import
    restart: unless-stopped
    networks:
      - keycloak-network
