version: '3'
networks:
  keycloak-network

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: keycloakpassword
    ports:
      - "3306:3306"
    networks:
      - keycloak-network

  keycloak:
    image: bitnami/keycloak
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_DATABASE_HOST: mariadb
      KEYCLOAK_DATABASE_PORT: 3306
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
      KC_DB: mariadb
      KC_DB_URL: "jdbc:mariadb://mariadb3306/keycloak"
      KC_DB_URL_PROPERTIES: "?useSSL=false"
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - keycloak-network

networks:
  keycloak-network
